# Generated by Django 5.0.4 on 2024-04-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_avatar_alter_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='avatar',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
